name: Generate page preview image

on: pull_request_target

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone jaoafa/jaoweb
        uses: actions/checkout@v2
        with:
          repository: jaoafa/jaoweb

      - name: Remove content
        run: rm -rf content

      - name: Clone jaoafa/jaoweb-docs
        uses: actions/checkout@v2
        with:
          path: content
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Download authors.json & categories.json
        run: |
          wget -O content/blog/authors.json https://raw.githubusercontent.com/jaoafa/jaoweb/master/content/blog/authors.json
          wget -O content/blog/categories.json https://raw.githubusercontent.com/jaoafa/jaoweb/master/content/blog/categories.json

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Japanese font
        run: sudo apt install fonts-ipafont-gothic fonts-ipafont-mincho

      - name: Install dependencies
        run: yarn

      - name: Nuxt build
        run: yarn cross-env NUXT_TELEMETRY_DISABLED=1 nuxt build

      - name: Nuxt generate
        run: yarn cross-env NUXT_TELEMETRY_DISABLED=1 nuxt generate

      - name: Check exists dist
        run: |
          ls -la
          test -d dist

      - name: Install dependencies in gen-page-preview
        working-directory: ./content/.github/gen-page-preview/
        run: |
          yarn
          npm install -D @playwright/test

      - name: Generate page screenshots
        working-directory: ./content/.github/gen-page-preview/
        run: yarn playwright test --config=playwright.config.ts --browser=firefox main.spec.ts
        env:
         ISSUE_NUMBER: ${{ github.event.number }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BASE_SHA: ${{ github.event.pull_request.base.sha }}
         IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
