name: Generate page preview image

on: pull_request_target

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Clone jaoafa/jaoweb
        uses: actions/checkout@v2
        with:
          repository: jaoafa/jaoweb

      - name: Remove content
        run: rm -rf content

      - name: Clone jaoafa/jaoweb-docs
        uses: actions/checkout@v2
        with:
          path: content
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Download authors.json & categories.json
        run: |
          wget -O content/blog/authors.json https://raw.githubusercontent.com/jaoafa/jaoweb/master/content/blog/authors.json
          wget -O content/blog/categories.json https://raw.githubusercontent.com/jaoafa/jaoweb/master/content/blog/categories.json

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Install dependencies in gen-page-preview
        working-directory: ./.github/gen-page-preview/
        run: yarn

      - name: Generate page screenshots
        working-directory: ./.github/gen-page-preview/
        run: yarn playwright test --config=playwright.config.ts main.spec.ts
        env:
         ISSUE_NUMBER: ${{ github.event.number }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         IMGUR_CLIENT_ID: ${{ secrets.IMGUR_CLIENT_ID }}
