name: Markdown header check

on: pull_request_target

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
           ref: ${{ github.event.pull_request.head.sha }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies & Compile
        working-directory: ./.github/scripts/
        run: |
          ls -la
          yarn
          yarn add --dev gray-matter typescript axios @types/node
          tsc markdown-header.ts

      - name: Run markdown-header
        run: |
          node .github/scripts/markdown-header.js | reviewdog -efm="%f: %m" -name="markdown-header" -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
