name: Markdown Lint Check on Pull Request

on: pull_request_target

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1.0.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Install markdownlint-cli
        run: npm install markdownlint-cli
      - name: Run markdownlint 1
        run: $(npm bin)/markdownlint "**/*.md" -c .markdownlint.jsonc --ignore node_modules 2>&1 | reviewdog -efm="%f:%l %m" -name="markdownlint" -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run markdownlint 2
        run: $(npm bin)/markdownlint "**/*.md" -c .markdownlint.jsonc --ignore node_modules 2>&1 | reviewdog -efm="%f:%l:%c %m" -name="markdownlint" -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
